-- MySQL Script generated by MySQL Workbench
-- 01/22/20 17:39:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`premios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`premios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ranking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `puesto` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `premios` VARCHAR(45) NULL,
  `puntos` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jugador` VARCHAR(45) NOT NULL,
  `administrador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
CREATE TABLE `mydb`.`user` (
  `id` int(11) NOT NULL,
  `user_name` varchar(60) NOT NULL,
  `email` varchar(80) NOT NULL,
  `password` varchar(100) NOT NULL,
  `user_pic` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_name` varchar(60) NOT NULL,
  `email` varchar(80) NOT NULL,
  `password` varchar(100) NOT NULL,
  `puntaje` VARCHAR(45)DEFAULT NULL ,
  `user_pic` varchar(100) DEFAULT NULL,
  `premios_id` INT DEFAULT NULL,
  `ranking_id` INT DEFAULT NULL,
  `tipo_id` INT DEFAULT NULL,
  `tipo_id1` INT DEFAULT NULL,
  PRIMARY KEY (`id`, `premios_id`, `ranking_id`, `tipo_id`, `tipo_id1`),
  CONSTRAINT `fk_users_premios1`
    FOREIGN KEY (`premios_id`)
    REFERENCES `mydb`.`premios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_ranking1`
    FOREIGN KEY (`ranking_id`)
    REFERENCES `mydb`.`ranking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_tipo1`
    FOREIGN KEY (`tipo_id1`)
    REFERENCES `mydb`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_premios1_idx` ON `mydb`.`users` (`premios_id` ASC);

CREATE INDEX `fk_users_ranking1_idx` ON `mydb`.`users` (`ranking_id` ASC);

CREATE INDEX `fk_users_tipo1_idx` ON `mydb`.`users` (`tipo_id1` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`perguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(100) NOT NULL,
  `id_respuestas` INT NULL,
  `administradores_id` INT NOT NULL,
  `tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `administradores_id`, `tipo_id`),
  CONSTRAINT `fk_perguntas_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `mydb`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_perguntas_tipo1_idx` ON `mydb`.`perguntas` (`tipo_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`tablero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tablero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `coordenadaY` VARCHAR(45) NOT NULL,
  `coordenadaX` VARCHAR(45) NOT NULL,
  `id_respuesta` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `respuestaC` VARCHAR(45) NOT NULL,
  `respuesta1I` VARCHAR(45) NOT NULL,
  `respuesta2I` VARCHAR(45) NOT NULL,
  `tablero_id` INT NOT NULL,
  `perguntas_id` INT NOT NULL,
  `perguntas_administradores_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tablero_id`, `perguntas_id`, `perguntas_administradores_id`),
  CONSTRAINT `fk_respuestas_tablero1`
    FOREIGN KEY (`tablero_id`)
    REFERENCES `mydb`.`tablero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_perguntas1`
    FOREIGN KEY (`perguntas_id` , `perguntas_administradores_id`)
    REFERENCES `mydb`.`perguntas` (`id` , `administradores_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_respuestas_tablero1_idx` ON `mydb`.`respuestas` (`tablero_id` ASC);

CREATE INDEX `fk_respuestas_perguntas1_idx` ON `mydb`.`respuestas` (`perguntas_id` ASC, `perguntas_administradores_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
